package constant;

import java.util.HashMap;
import java.util.Map;

public class Constants {
	
	public static final String BULLS_SHARES = "ACSEL,ADANA,ADBGR,ADEL,ADESE,ADNAC,AEFES,AFYON,AGYO,AKBNK,AKCNS,AKENR,AKFGY,AKGRT,AKGUV,AKMGY,AKSA,AKSEN,AKSGY,AKSUE,ALARK,ALBRK,ALCAR,ALCTL,ALGYO,ALKA,ALKIM,ALYAG,ANACM,ANELE,ANHYT,ANSGR,ARCLK,ARENA,ARMDA,ARSAN,ARTI,ASELS,ASLAN,ASUZU,ATAGY,ATEKS,ATLAS,ATPET,ATSYH,AVGYO,AVHOL,AVISA,AVOD,AVTUR, AYCES,AYEN,AYGAZ,BAGFS,BAKAB,BANVT,BERA.IS,BEYAZ,BFREN,BIMAS,BIZIM,BJKAS,BLCYT,BMELK,BNKTRf,BNTAS,BOLUC,BOSSA,BOYP,BRISA,BRKO,BRKSN,BRMEN,BRSAN,BRYAT,BSOKE,BTCIM,BUCIM,BURCE,BURVA,CCOLA,CELHA,CEMAS,CEMTS,CIMSA,CLEBI,CMBTN,CMENT,COMDO,COSMO,CRDFA,CRFSA,CUSAN,DAGHL,DAGI,DARDL,DENCM,DENGE,DENIZ,DERIM, DESA,DESPC,DEVA,DGATE,DGGYO,DGKLB,DGZTE,DIRIT,DITAS,DJISTf,DMSAS,DOAS,DOBUR,DOCO,DOGUB,DOHOL,DURDO,DYOBY,DZGYO,ECBYO,ECILC,ECZYT,EDIP,EGCYO,EGEEN,EGGUB,EGLYO,EGPRO,EGSER,EKGYO,EMKEL,EMNIS,ENKAI,EPLAS,ERBOS,EREGL,ERSU,ESCOM,ESEMS,ETILR,ETYAT,EUHOL,EUKYO,EUYO,FBISTf,FENER,FINBN,FLAP,FMIZP,FONET, FROTO,GARAN,GARFA,GDKGS,GEDZA,GENTS,GEREL,GLDTRf,GLRYH,GLYHO,GMSTRf,GOLDPf,GOLTS,GOODY,GOZDE,GRNYO,GSDDE,GSDHO,GSRAY,GUBRF,GUSGR,GYHOL,HALKB,HATEK,HDFGS,HEKTS,HLGYO,HURGZ,ICBCT,IDGYO,IEYHO,IHEVA,IHGZT,IHLAS,IHLGM,IHYAY,INDES,INFO,INTEM,IPEKE,ISCTR,ISDMR,ISFIN,ISGSY,ISGYO,ISMEN,IST30f,ISY30f,ISYAT,ITTFH, IZFAS,IZMDC,IZOCM,IZTAR,JANTS,KAPLM,KAREL,KARSN,KARTN,KATMR,KCHOL,KENT,KERVN,KERVT,KIPA,KLGYO,KLMSN,KLNMA,KNFRT,KONYA,KORDS,KOZAA,KOZAL,KPHOL,KRDMA,KRDMB,KRDMD,KRGYO,KRONT,KRSAN,KRSTL,KRTEK,KUTPO,KUYAS,LIDFA,LINK,LKMNH,LOGO,LUKSK,MAALT,MAKTK,MARKA,MARTI,MAVI.IS,MCTAS,MEGAP,MEPET,MERIT,MERKO,METAL, METRO,METUR,MGROS,MIPAZ,MMCAS,MNDRS,MRDIN,MRGYO,MRSHL,MSGYO,MZHLD,NETAS,NIBAS,NTHOL,NUGYO,NUHCM,ODAS,OLMIP,ORGE,OSTIM,OTKAR,OYAYO,OYLUM,OZBAL,OZGYO,OZKGY,OZRDN,PAGYO,PARSN,PEGYO,PENGD,PETKM,PETUN,PGSUS,PIMAS,PINSU,PKART,PKENT,PMVR3,PNSUT,POLHO,POLTK,PRKAB,PRKME,PRZMA,PSDTC,RAYSG,RHEAG,RODRG,ROYAL, RTALB,RYGYO,RYSAS,SAHOL,SALIX.IS,SAMAT,SANEL,SANFM,SANKO,SARKY,SASA,SAYAS,SEKFK,SEKUR,SELEC,SEYKM,SILVR,SISE,SKBNK,SKTAS,SNGYO,SNKRN,SNPAM,SODA,SONME,SRVGY,TACTR,TATGD,TAVHL,TBORG,TCELL,TEKTU,TGSAS,THYAO,TIRE,TKFEN,TKNSA,TKURU,TMPOL,TMSN,TOASO,TRCAS,TRGYO,TRKCM,TSGYO,TSKB,TSPOR,TTKOM,TTRAK,TUCLK, TUKAS,TUPRS,TURGG,UFUK,ULAS,ULKER,ULUSE,ULUUN,UNYEC,USAK,USDTRf,UTPYA,VAKBN,VAKFN,VAKKO,VANGD,VERTU,VERUS,VESBE,VESTL,VKFYO,VKGYO,VKING,YATAS,YAYLA,YAZIC,YESIL,YGGYO,YGYO,YKBNK,YKGYO,YUNSA,YYAPI,ZOREN";
	public static final String BULLS_BASE_URL = "https://www.turkishbulls.com/SignalPage.aspx";
	public static final String BULLS_LANG_ATTR = "lang=";
	public static final String BULLS_SHARE_ATTR = "Ticker=";
	public static final Map<String, String> BULLS_LANGUAGES = new HashMap<>();
	
	
	public static final String SHARE_LAST_PRICE_IN_TL_SPAN_ID = "MainContent_LastClose";
	public static final String SHARE_LAST_FORMATION_SPAN_ID = "MainContent_LastPattern";
	public static final String SHARE_LONG_NAME_SPAN_ID = "MainContent_Name";
	public static final String SHARE_LAST_SIGNAL_SPAN_ID= "MainContent_LastSignal";
	public static final String SHARE_SHORT_CODE_SPAN_ID= "MainContent_CompanyTicker";
	public static final String SHARE_SIGNAL_HISTORY_TABLE_24_ID = "MainContent_signalpagehistory_PatternHistory24_DXMainTable";
	public static final String SHARE_SIGNAL_HISTORY_TABLE_12_ID = "MainContent_signalpagehistory_PatternHistory12_DXMainTable";
	public static final String SHARE_SIGNAL_HISTORY_TABLE_06_ID = "MainContent_signalpagehistory_PatternHistory6_DXMainTable";
	
	public static final String DATE_FORMAT_SITE = "dd/MM/yyyy";
	
	
	public static final Map<String, String> SHARE_SIGNAL_HISTORY_ACTIONS = new HashMap<>();
	
	static 
	{
		SHARE_SIGNAL_HISTORY_ACTIONS.put("SAT", "SAT");
		SHARE_SIGNAL_HISTORY_ACTIONS.put("AL", "AL");

		BULLS_LANGUAGES.put("tr", "tr");
		BULLS_LANGUAGES.put("en", "en");
	}
	
}
